spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_mgmt
    username: root
    password: shiva
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
contactInfo: 
    contactNumber: 1234567890
    emailAddress: demo@gmail.com
